
/*CREATE TABLE*/

CREATE TABLE photo_param (
    "nbContours" INTEGER,
    "isPortrait" INTEGER,
    "path" TEXT,
    "iso" INTEGER,
    "shutterspeed" DOUBLE,
    "aperture" DOUBLE,
    "focus" INTEGER,
    "nbfaces" INTEGER,
    "dominant_color" INTEGER,
    "global_hue" INTEGER,
    "global_saturation" INTEGER,
    "global_lightness" INTEGER,
    "mean_red" INTEGER,
    "mean_green" INTEGER,
    "mean_blue" INTEGER,
    "var_red" INTEGER,
    "var_green" INTEGER,
    "var_blue" INTEGER,
    "var_h" INTEGER,
    "var_s" INTEGER,
    "var_v" INTEGER
)

//Mettre le script SQL dans le champ prévu à cet effet, placer le curseur sur la première ligne et clique sur la 
// double flèche verte "Executer plusieurs instructions SQL en lot ..."

/*DATA*/

insert into photo_param ("nbContours", "isPortrait", "path", "iso", "shutterspeed", "aperture", "focus", "nbfaces", "dominant_color", "global_hue", "global_saturation", "global_lightness", "mean_red", "mean_green", "mean_blue", "var_red", "var_green", "var_blue", "var_h", "var_s", "var_v") values ('23', '0', '../db/img/done/abstract.jpg', '400', '0.001', '5.6', '0', '0', '3', '77', '41', '143', '130', '134', '140', '31', '34', '10', '33', '37', '28');
insert into photo_param ("nbContours", "isPortrait", "path", "iso", "shutterspeed", "aperture", "focus", "nbfaces", "dominant_color", "global_hue", "global_saturation", "global_lightness", "mean_red", "mean_green", "mean_blue", "var_red", "var_green", "var_blue", "var_h", "var_s", "var_v") values ('1454', '0', '../db/img/done/decors-jour.jpg', '100', '0.003125', '3.5', '0', '0', '1', '21', '109', '47', '47', '42', '29', '5', '18', '13', '9', '2', '5');
insert into photo_param ("nbContours", "isPortrait", "path", "iso", "shutterspeed", "aperture", "focus", "nbfaces", "dominant_color", "global_hue", "global_saturation", "global_lightness", "mean_red", "mean_green", "mean_blue", "var_red", "var_green", "var_blue", "var_h", "var_s", "var_v") values ('200', '0', '../db/img/done/macro.jpg', '100', '0.05', '22', '0', '0', '7', '40', '59', '113', '110', '104', '88', '53', '49', '48', '41', '43', '53');
insert into photo_param ("nbContours", "isPortrait", "path", "iso", "shutterspeed", "aperture", "focus", "nbfaces", "dominant_color", "global_hue", "global_saturation", "global_lightness", "mean_red", "mean_green", "mean_blue", "var_red", "var_green", "var_blue", "var_h", "var_s", "var_v") values ('1015', '0', '../db/img/done/nuit-fast.jpg', '1600', '0.0769231', '3.5', '0', '0', '4', '13', '195', '99', '98', '56', '26', '25', '30', '38', '40', '39', '25');
insert into photo_param ("nbContours", "isPortrait", "path", "iso", "shutterspeed", "aperture", "focus", "nbfaces", "dominant_color", "global_hue", "global_saturation", "global_lightness", "mean_red", "mean_green", "mean_blue", "var_red", "var_green", "var_blue", "var_h", "var_s", "var_v") values ('2382', '0', '../db/img/done/nuit.jpg', '100', '30', '22', '0', '0', '1', '19', '201', '64', '64', '44', '17', '8', '13', '12', '12', '12', '8');
insert into photo_param ("nbContours", "isPortrait", "path", "iso", "shutterspeed", "aperture", "focus", "nbfaces", "dominant_color", "global_hue", "global_saturation", "global_lightness", "mean_red", "mean_green", "mean_blue", "var_red", "var_green", "var_blue", "var_h", "var_s", "var_v") values ('4372', '0', '../db/img/done/paysage-long-exposure.jpg', '100', '13', '22', '0', '0', '1', '29', '211', '34', '33', '25', '16', '13', '12', '13', '14', '3', '13');
insert into photo_param ("nbContours", "isPortrait", "path", "iso", "shutterspeed", "aperture", "focus", "nbfaces", "dominant_color", "global_hue", "global_saturation", "global_lightness", "mean_red", "mean_green", "mean_blue", "var_red", "var_green", "var_blue", "var_h", "var_s", "var_v") values ('13662', '0', '../db/img/done/paysage-long-pose.jpg', '100', '30', '10', '0', '0', '5', '15', '164', '105', '105', '75', '43', '9', '14', '16', '3', '9', '9');
insert into photo_param ("nbContours", "isPortrait", "path", "iso", "shutterspeed", "aperture", "focus", "nbfaces", "dominant_color", "global_hue", "global_saturation", "global_lightness", "mean_red", "mean_green", "mean_blue", "var_red", "var_green", "var_blue", "var_h", "var_s", "var_v") values ('7034', '0', '../db/img/done/paysage-nuit.jpg', '100', '20', '22', '0', '0', '1', '16', '213', '55', '55', '35', '14', '15', '13', '14', '14', '8', '15');
insert into photo_param ("nbContours", "isPortrait", "path", "iso", "shutterspeed", "aperture", "focus", "nbfaces", "dominant_color", "global_hue", "global_saturation", "global_lightness", "mean_red", "mean_green", "mean_blue", "var_red", "var_green", "var_blue", "var_h", "var_s", "var_v") values ('2536', '0', '../db/img/done/portrait-fast.jpg', '400', '0.0008', '3.5', '0', '0', '7', '46', '64', '114', '110', '99', '94', '40', '29', '24', '42', '18', '40');
insert into photo_param ("nbContours", "isPortrait", "path", "iso", "shutterspeed", "aperture", "focus", "nbfaces", "dominant_color", "global_hue", "global_saturation", "global_lightness", "mean_red", "mean_green", "mean_blue", "var_red", "var_green", "var_blue", "var_h", "var_s", "var_v") values ('1189', '0', '../db/img/done/portrait-fast-night.jpg', '400', '0.5', '4', '0', '0', '5', '24', '124', '123', '122', '88', '60', '9', '28', '7', '37', '28', '9');
insert into photo_param ("nbContours", "isPortrait", "path", "iso", "shutterspeed", "aperture", "focus", "nbfaces", "dominant_color", "global_hue", "global_saturation", "global_lightness", "mean_red", "mean_green", "mean_blue", "var_red", "var_green", "var_blue", "var_h", "var_s", "var_v") values ('985', '0', '../db/img/done/sombre-fast.jpg', '400', '0.0333333', '3.5', '0', '0', '1', '29', '128', '41', '40', '36', '25', '21', '31', '36', '35', '33', '21');
insert into photo_param ("nbContours", "isPortrait", "path", "iso", "shutterspeed", "aperture", "focus", "nbfaces", "dominant_color", "global_hue", "global_saturation", "global_lightness", "mean_red", "mean_green", "mean_blue", "var_red", "var_green", "var_blue", "var_h", "var_s", "var_v") values ('2110', '0', '../db/img/done/subject-dark.jpg', '400', '0.04', '3.5', '0', '0', '1', '38', '102', '58', '55', '51', '46', '4', '15', '8', '1', '24', '3');
insert into photo_param ("nbContours", "isPortrait", "path", "iso", "shutterspeed", "aperture", "focus", "nbfaces", "dominant_color", "global_hue", "global_saturation", "global_lightness", "mean_red", "mean_green", "mean_blue", "var_red", "var_green", "var_blue", "var_h", "var_s", "var_v") values ('14461', '0', '../db/img/done/subject.jpg', '100', '0.0666667', '5', '0', '0', '6', '30', '114', '77', '76', '65', '47', '9', '7', '15', '2', '15', '9');
insert into photo_param ("nbContours", "isPortrait", "path", "iso", "shutterspeed", "aperture", "focus", "nbfaces", "dominant_color", "global_hue", "global_saturation", "global_lightness", "mean_red", "mean_green", "mean_blue", "var_red", "var_green", "var_blue", "var_h", "var_s", "var_v") values ('1869', '0', '../db/img/done/super-long-exposure.jpg', '400', '326', '4', '0', '0', '4', '10', '138', '87', '86', '54', '41', '25', '20', '16', '22', '20', '25');
insert into photo_param ("nbContours", "isPortrait", "path", "iso", "shutterspeed", "aperture", "focus", "nbfaces", "dominant_color", "global_hue", "global_saturation", "global_lightness", "mean_red", "mean_green", "mean_blue", "var_red", "var_green", "var_blue", "var_h", "var_s", "var_v") values ('377', '1', '../db/portrait_img/portrait5.jpg', '0', '0.05', '4.5', '0', '1', '1', '0', '0', '43', '43', '43', '43', '62', '62', '62', '72', '72', '62');
insert into photo_param ("nbContours", "isPortrait", "path", "iso", "shutterspeed", "aperture", "focus", "nbfaces", "dominant_color", "global_hue", "global_saturation", "global_lightness", "mean_red", "mean_green", "mean_blue", "var_red", "var_green", "var_blue", "var_h", "var_s", "var_v") values ('632', '0', '../db/portrait_img/portrait6.jpg', '200', '0.0166667', '14', '0', '0', '1', '0', '0', '40', '40', '40', '40', '49', '49', '49', '64', '64', '49');
insert into photo_param ("nbContours", "isPortrait", "path", "iso", "shutterspeed", "aperture", "focus", "nbfaces", "dominant_color", "global_hue", "global_saturation", "global_lightness", "mean_red", "mean_green", "mean_blue", "var_red", "var_green", "var_blue", "var_h", "var_s", "var_v") values ('5629', '0', '../db/toadd/openphotonet_02_IX_2008_344.JPG', '50', '0.005', '5.6', '0', '0', '9', '106', '58', '184', '144', '160', '183', '13', '11', '7', '14', '9', '14');
insert into photo_param ("nbContours", "isPortrait", "path", "iso", "shutterspeed", "aperture", "focus", "nbfaces", "dominant_color", "global_hue", "global_saturation", "global_lightness", "mean_red", "mean_green", "mean_blue", "var_red", "var_green", "var_blue", "var_h", "var_s", "var_v") values ('20915', '0', '../db/toadd/openphotonet_02_IX_2008_770.JPG', '64', '0.0166667', '3.5', '0', '0', '7', '37', '119', '128', '124', '104', '77', '3', '10', '11', '9', '18', '1');
insert into photo_param ("nbContours", "isPortrait", "path", "iso", "shutterspeed", "aperture", "focus", "nbfaces", "dominant_color", "global_hue", "global_saturation", "global_lightness", "mean_red", "mean_green", "mean_blue", "var_red", "var_green", "var_blue", "var_h", "var_s", "var_v") values ('37160', '0', '../db/toadd/openphotonet_IMG_0740.jpg', '0', '0.008', '8', '0', '0', '7', '46', '96', '151', '135', '149', '117', '10', '12', '12', '14', '6', '8');
insert into photo_param ("nbContours", "isPortrait", "path", "iso", "shutterspeed", "aperture", "focus", "nbfaces", "dominant_color", "global_hue", "global_saturation", "global_lightness", "mean_red", "mean_green", "mean_blue", "var_red", "var_green", "var_blue", "var_h", "var_s", "var_v") values ('3118', '0', '../db/toadd/openphotonet_PC137261.jpg', '64', '0.000625', '8', '0', '0', '3', '50', '50', '114', '109', '110', '98', '22', '11', '17', '18', '14', '23');
insert into photo_param ("nbContours", "isPortrait", "path", "iso", "shutterspeed", "aperture", "focus", "nbfaces", "dominant_color", "global_hue", "global_saturation", "global_lightness", "mean_red", "mean_green", "mean_blue", "var_red", "var_green", "var_blue", "var_h", "var_s", "var_v") values ('27477', '0', '../db/toadd/opl_park-eshkol.jpg', '50', '0.003125', '5', '0', '0', '7', '42', '73', '160', '153', '157', '128', '21', '17', '4', '17', '18', '22');
insert into photo_param ("nbContours", "isPortrait", "path", "iso", "shutterspeed", "aperture", "focus", "nbfaces", "dominant_color", "global_hue", "global_saturation", "global_lightness", "mean_red", "mean_green", "mean_blue", "var_red", "var_green", "var_blue", "var_h", "var_s", "var_v") values ('2426', '0', '../../photos/3/33.jpg', '100', '0.00625', '11', '0', '0', '8', '86', '178', '113', '26', '64', '102', '42', '30', '11', '20', '43', '42');
insert into photo_param ("nbContours", "isPortrait", "path", "iso", "shutterspeed", "aperture", "focus", "nbfaces", "dominant_color", "global_hue", "global_saturation", "global_lightness", "mean_red", "mean_green", "mean_blue", "var_red", "var_green", "var_blue", "var_h", "var_s", "var_v") values ('6510', '0', '../../photos/3/35.jpg', '400', '30', '4', '0', '0', '7', '65', '115', '131', '90', '103', '125', '26', '6', '22', '4', '12', '20');
insert into photo_param ("nbContours", "isPortrait", "path", "iso", "shutterspeed", "aperture", "focus", "nbfaces", "dominant_color", "global_hue", "global_saturation", "global_lightness", "mean_red", "mean_green", "mean_blue", "var_red", "var_green", "var_blue", "var_h", "var_s", "var_v") values ('791', '0', '../../photos/4/44.jpg', '400', '0.003125', '2.8', '0', '0', '1', '99', '111', '65', '37', '53', '65', '28', '28', '33', '40', '13', '39');
insert into photo_param ("nbContours", "isPortrait", "path", "iso", "shutterspeed", "aperture", "focus", "nbfaces", "dominant_color", "global_hue", "global_saturation", "global_lightness", "mean_red", "mean_green", "mean_blue", "var_red", "var_green", "var_blue", "var_h", "var_s", "var_v") values ('349', '0', '../../photos/4/47.jpg', '100', '0.05', '10', '0', '0', '2', '102', '15', '201', '191', '195', '201', '30', '31', '28', '28', '19', '29');
insert into photo_param ("nbContours", "isPortrait", "path", "iso", "shutterspeed", "aperture", "focus", "nbfaces", "dominant_color", "global_hue", "global_saturation", "global_lightness", "mean_red", "mean_green", "mean_blue", "var_red", "var_green", "var_blue", "var_h", "var_s", "var_v") values ('624', '0', '../../photos/4/48.jpg', '100', '0.0025', '2.8', '0', '0', '3', '89', '34', '171', '158', '165', '166', '32', '34', '22', '31', '19', '30');
insert into photo_param ("nbContours", "isPortrait", "path", "iso", "shutterspeed", "aperture", "focus", "nbfaces", "dominant_color", "global_hue", "global_saturation", "global_lightness", "mean_red", "mean_green", "mean_blue", "var_red", "var_green", "var_blue", "var_h", "var_s", "var_v") values ('14171', '0', '../../photos/4/49.jpg', '100', '0.125', '10', '0', '0', '1', '20', '136', '58', '58', '44', '29', '19', '29', '32', '33', '2', '19');
insert into photo_param ("nbContours", "isPortrait", "path", "iso", "shutterspeed", "aperture", "focus", "nbfaces", "dominant_color", "global_hue", "global_saturation", "global_lightness", "mean_red", "mean_green", "mean_blue", "var_red", "var_green", "var_blue", "var_h", "var_s", "var_v") values ('30283', '0', '../../photos/8/96.JPG', '100', '0.00125', '4', '0', '0', '7', '65', '63', '161', '141', '148', '142', '15', '8', '7', '12', '13', '8');
insert into photo_param ("nbContours", "isPortrait", "path", "iso", "shutterspeed", "aperture", "focus", "nbfaces", "dominant_color", "global_hue", "global_saturation", "global_lightness", "mean_red", "mean_green", "mean_blue", "var_red", "var_green", "var_blue", "var_h", "var_s", "var_v") values ('8667', '0', '../../photos/7/92.jpg', '100', '0.0008', '5.6', '0', '0', '7', '49', '124', '140', '123', '133', '100', '32', '18', '16', '22', '20', '36');
insert into photo_param ("nbContours", "isPortrait", "path", "iso", "shutterspeed", "aperture", "focus", "nbfaces", "dominant_color", "global_hue", "global_saturation", "global_lightness", "mean_red", "mean_green", "mean_blue", "var_red", "var_green", "var_blue", "var_h", "var_s", "var_v") values ('4627', '0', '../../photos/10/128.jpg', '100', '0.0005', '5', '0', '0', '8', '73', '77', '123', '110', '114', '115', '36', '19', '31', '33', '31', '34');
insert into photo_param ("nbContours", "isPortrait", "path", "iso", "shutterspeed", "aperture", "focus", "nbfaces", "dominant_color", "global_hue", "global_saturation", "global_lightness", "mean_red", "mean_green", "mean_blue", "var_red", "var_green", "var_blue", "var_h", "var_s", "var_v") values ('1599', '0', '../../photos/11/133.jpg', '100', '0.0008', '5', '0', '0', '7', '66', '115', '150', '90', '116', '134', '44', '16', '27', '39', '16', '38');
insert into photo_param ("nbContours", "isPortrait", "path", "iso", "shutterspeed", "aperture", "focus", "nbfaces", "dominant_color", "global_hue", "global_saturation", "global_lightness", "mean_red", "mean_green", "mean_blue", "var_red", "var_green", "var_blue", "var_h", "var_s", "var_v") values ('16220', '0', '../../photos/11/MATCH1_11.jpg', '64', '0.007343', '5.6', '0', '0', '7', '66', '58', '103', '95', '100', '90', '15', '11', '16', '12', '15', '13');
insert into photo_param ("nbContours", "isPortrait", "path", "iso", "shutterspeed", "aperture", "focus", "nbfaces", "dominant_color", "global_hue", "global_saturation", "global_lightness", "mean_red", "mean_green", "mean_blue", "var_red", "var_green", "var_blue", "var_h", "var_s", "var_v") values ('27515', '0', '../../photos/11/MATCH4_121.JPG', '80', '0.025', '4', '0', '0', '3', '62', '35', '144', '138', '136', '133', '13', '1', '4', '9', '0', '12');
insert into photo_param ("nbContours", "isPortrait", "path", "iso", "shutterspeed", "aperture", "focus", "nbfaces", "dominant_color", "global_hue", "global_saturation", "global_lightness", "mean_red", "mean_green", "mean_blue", "var_red", "var_green", "var_blue", "var_h", "var_s", "var_v") values ('7083', '0', '../../photos/11/_MG_5668.JPG', '100', '0.0166667', '18', '0', '0', '8', '79', '66', '142', '115', '125', '132', '15', '4', '15', '9', '14', '12');
insert into photo_param ("nbContours", "isPortrait", "path", "iso", "shutterspeed", "aperture", "focus", "nbfaces", "dominant_color", "global_hue", "global_saturation", "global_lightness", "mean_red", "mean_green", "mean_blue", "var_red", "var_green", "var_blue", "var_h", "var_s", "var_v") values ('49953', '0', '../../photos/11/_MG_5684.JPG', '100', '0.0025', '5.6', '0', '0', '6', '27', '124', '113', '111', '106', '59', '11', '11', '15', '15', '14', '11');
insert into photo_param ("nbContours", "isPortrait", "path", "iso", "shutterspeed", "aperture", "focus", "nbfaces", "dominant_color", "global_hue", "global_saturation", "global_lightness", "mean_red", "mean_green", "mean_blue", "var_red", "var_green", "var_blue", "var_h", "var_s", "var_v") values ('15501', '0', '../../photos/11/_MG_5750.JPG', '100', '0.001', '5.6', '0', '0', '7', '71', '53', '155', '149', '152', '142', '15', '15', '9', '13', '13', '14');
insert into photo_param ("nbContours", "isPortrait", "path", "iso", "shutterspeed", "aperture", "focus", "nbfaces", "dominant_color", "global_hue", "global_saturation", "global_lightness", "mean_red", "mean_green", "mean_blue", "var_red", "var_green", "var_blue", "var_h", "var_s", "var_v") values ('38312', '0', '../../photos/11/_MG_5777.JPG', '100', '0.05', '22', '0', '0', '7', '41', '61', '119', '111', '118', '89', '13', '12', '11', '13', '7', '15');
insert into photo_param ("nbContours", "isPortrait", "path", "iso", "shutterspeed", "aperture", "focus", "nbfaces", "dominant_color", "global_hue", "global_saturation", "global_lightness", "mean_red", "mean_green", "mean_blue", "var_red", "var_green", "var_blue", "var_h", "var_s", "var_v") values ('10770', '0', '../../photos/12/_MG_5789.JPG', '100', '0.003125', '5.6', '0', '0', '6', '29', '99', '118', '114', '114', '71', '11', '16', '15', '7', '3', '11');
insert into photo_param ("nbContours", "isPortrait", "path", "iso", "shutterspeed", "aperture", "focus", "nbfaces", "dominant_color", "global_hue", "global_saturation", "global_lightness", "mean_red", "mean_green", "mean_blue", "var_red", "var_green", "var_blue", "var_h", "var_s", "var_v") values ('275', '0', '../../photos/12/_MG_5826.JPG', '100', '0.0025', '5.6', '0', '0', '3', '29', '44', '119', '118', '113', '97', '12', '14', '10', '9', '13', '12');
insert into photo_param ("nbContours", "isPortrait", "path", "iso", "shutterspeed", "aperture", "focus", "nbfaces", "dominant_color", "global_hue", "global_saturation", "global_lightness", "mean_red", "mean_green", "mean_blue", "var_red", "var_green", "var_blue", "var_h", "var_s", "var_v") values ('29835', '0', '../../photos/12/_MG_5858.JPG', '100', '0.000625', '3.5', '0', '0', '7', '47', '61', '119', '115', '114', '99', '14', '14', '15', '14', '11', '15');
insert into photo_param ("nbContours", "isPortrait", "path", "iso", "shutterspeed", "aperture", "focus", "nbfaces", "dominant_color", "global_hue", "global_saturation", "global_lightness", "mean_red", "mean_green", "mean_blue", "var_red", "var_green", "var_blue", "var_h", "var_s", "var_v") values ('696', '0', '../../photos/12/_MG_5891.JPG', '100', '0.002', '5.6', '0', '0', '6', '32', '173', '83', '79', '80', '28', '14', '8', '4', '2', '1', '13');
insert into photo_param ("nbContours", "isPortrait", "path", "iso", "shutterspeed", "aperture", "focus", "nbfaces", "dominant_color", "global_hue", "global_saturation", "global_lightness", "mean_red", "mean_green", "mean_blue", "var_red", "var_green", "var_blue", "var_h", "var_s", "var_v") values ('9119', '0', '../../photos/12/_MG_5925.JPG', '100', '0.0005', '3.5', '0', '0', '3', '58', '50', '141', '128', '128', '127', '3', '16', '4', '10', '7', '12');
insert into photo_param ("nbContours", "isPortrait", "path", "iso", "shutterspeed", "aperture", "focus", "nbfaces", "dominant_color", "global_hue", "global_saturation", "global_lightness", "mean_red", "mean_green", "mean_blue", "var_red", "var_green", "var_blue", "var_h", "var_s", "var_v") values ('7578', '0', '../../photos/12/_MG_5960.JPG', '100', '0.0008', '3.5', '0', '0', '3', '40', '50', '113', '109', '106', '95', '11', '14', '9', '7', '11', '12');
insert into photo_param ("nbContours", "isPortrait", "path", "iso", "shutterspeed", "aperture", "focus", "nbfaces", "dominant_color", "global_hue", "global_saturation", "global_lightness", "mean_red", "mean_green", "mean_blue", "var_red", "var_green", "var_blue", "var_h", "var_s", "var_v") values ('5057', '0', '../../photos/12/_MG_6011.JPG', '100', '0.02', '3.5', '0', '0', '3', '70', '36', '117', '109', '111', '113', '15', '10', '6', '14', '11', '13');
insert into photo_param ("nbContours", "isPortrait", "path", "iso", "shutterspeed", "aperture", "focus", "nbfaces", "dominant_color", "global_hue", "global_saturation", "global_lightness", "mean_red", "mean_green", "mean_blue", "var_red", "var_green", "var_blue", "var_h", "var_s", "var_v") values ('827', '0', '../../photos/12/_MG_6029.JPG', '100', '0.4', '5.6', '0', '0', '5', '21', '153', '124', '123', '103', '50', '9', '15', '9', '10', '8', '9');
insert into photo_param ("nbContours", "isPortrait", "path", "iso", "shutterspeed", "aperture", "focus", "nbfaces", "dominant_color", "global_hue", "global_saturation", "global_lightness", "mean_red", "mean_green", "mean_blue", "var_red", "var_green", "var_blue", "var_h", "var_s", "var_v") values ('4403', '0', '../../photos/12/_MG_6070.JPG', '100', '0.0025', '5.6', '0', '0', '3', '32', '31', '104', '103', '103', '91', '7', '8', '16', '9', '14', '7');
insert into photo_param ("nbContours", "isPortrait", "path", "iso", "shutterspeed", "aperture", "focus", "nbfaces", "dominant_color", "global_hue", "global_saturation", "global_lightness", "mean_red", "mean_green", "mean_blue", "var_red", "var_green", "var_blue", "var_h", "var_s", "var_v") values ('809', '0', '../../photos/14/tumblr_n1gayrieM81sdyj9lo1_1280.jpg', '320', '0.00625', '22', '0', '0', '7', '54', '133', '101', '82', '93', '81', '34', '8', '42', '32', '40', '39');
insert into photo_param ("nbContours", "isPortrait", "path", "iso", "shutterspeed", "aperture", "focus", "nbfaces", "dominant_color", "global_hue", "global_saturation", "global_lightness", "mean_red", "mean_green", "mean_blue", "var_red", "var_green", "var_blue", "var_h", "var_s", "var_v") values ('5208', '0', '../../photos/14/tumblr_n4e0r2GgRG1sdyj9lo1_1280.jpg', '100', '0.005', '5.6', '0', '0', '7', '39', '111', '96', '93', '84', '49', '25', '40', '30', '32', '30', '24');
insert into photo_param ("nbContours", "isPortrait", "path", "iso", "shutterspeed", "aperture", "focus", "nbfaces", "dominant_color", "global_hue", "global_saturation", "global_lightness", "mean_red", "mean_green", "mean_blue", "var_red", "var_green", "var_blue", "var_h", "var_s", "var_v") values ('1640', '0', '../../photos/14/tumblr_n4e0trKVoo1sdyj9lo1_1280.jpg', '400', '0.003125', '2.8', '0', '0', '8', '100', '85', '78', '49', '64', '78', '35', '42', '31', '22', '42', '43');
insert into photo_param ("nbContours", "isPortrait", "path", "iso", "shutterspeed", "aperture", "focus", "nbfaces", "dominant_color", "global_hue", "global_saturation", "global_lightness", "mean_red", "mean_green", "mean_blue", "var_red", "var_green", "var_blue", "var_h", "var_s", "var_v") values ('18360', '0', '../../imgtest/cheminfer.JPG', '80', '0.003125', '5.6', '0', '0', '7', '57', '54', '159', '151', '149', '141', '26', '12', '25', '18', '16', '24');
insert into photo_param ("nbContours", "isPortrait", "path", "iso", "shutterspeed", "aperture", "focus", "nbfaces", "dominant_color", "global_hue", "global_saturation", "global_lightness", "mean_red", "mean_green", "mean_blue", "var_red", "var_green", "var_blue", "var_h", "var_s", "var_v") values ('10829', '0', '../../../../Bureau/estetimage/dump/001.jpg', '125', '0.004', '4.5', '0', '0', '7', '46', '71', '128', '113', '127', '93', '25', '13', '40', '24', '35', '21');
insert into photo_param ("nbContours", "isPortrait", "path", "iso", "shutterspeed", "aperture", "focus", "nbfaces", "dominant_color", "global_hue", "global_saturation", "global_lightness", "mean_red", "mean_green", "mean_blue", "var_red", "var_green", "var_blue", "var_h", "var_s", "var_v") values ('4978', '0', '../../../../Bureau/estetimage/dump/002.jpg', '80', '0.001', '3.2', '0', '0', '7', '54', '96', '147', '135', '142', '114', '33', '34', '15', '30', '39', '35');
insert into photo_param ("nbContours", "isPortrait", "path", "iso", "shutterspeed", "aperture", "focus", "nbfaces", "dominant_color", "global_hue", "global_saturation", "global_lightness", "mean_red", "mean_green", "mean_blue", "var_red", "var_green", "var_blue", "var_h", "var_s", "var_v") values ('3788', '0', '../../../../Bureau/estetimage/dump/004.jpg', '100', '0.008', '5.6', '4294970000', '0', '7', '49', '107', '133', '122', '129', '84', '43', '39', '58', '46', '45', '44');
insert into photo_param ("nbContours", "isPortrait", "path", "iso", "shutterspeed", "aperture", "focus", "nbfaces", "dominant_color", "global_hue", "global_saturation", "global_lightness", "mean_red", "mean_green", "mean_blue", "var_red", "var_green", "var_blue", "var_h", "var_s", "var_v") values ('3718', '0', '../../../../Bureau/estetimage/dump/005.jpg', '80', '0.00555556', '9.5', '0', '0', '7', '70', '118', '157', '111', '145', '118', '40', '50', '44', '20', '41', '21');
insert into photo_param ("nbContours", "isPortrait", "path", "iso", "shutterspeed", "aperture", "focus", "nbfaces", "dominant_color", "global_hue", "global_saturation", "global_lightness", "mean_red", "mean_green", "mean_blue", "var_red", "var_green", "var_blue", "var_h", "var_s", "var_v") values ('4644', '0', '../../../../Bureau/estetimage/dump/006.jpg', '500', '0.00125', '5', '0', '0', '7', '50', '121', '126', '116', '122', '73', '35', '39', '30', '38', '39', '33');
insert into photo_param ("nbContours", "isPortrait", "path", "iso", "shutterspeed", "aperture", "focus", "nbfaces", "dominant_color", "global_hue", "global_saturation", "global_lightness", "mean_red", "mean_green", "mean_blue", "var_red", "var_green", "var_blue", "var_h", "var_s", "var_v") values ('10380', '0', '../../../../Bureau/estetimage/dump/007.jpg', '200', '0.0025', '3.5', '0', '0', '7', '45', '103', '118', '108', '115', '86', '43', '43', '16', '37', '42', '42');
insert into photo_param ("nbContours", "isPortrait", "path", "iso", "shutterspeed", "aperture", "focus", "nbfaces", "dominant_color", "global_hue", "global_saturation", "global_lightness", "mean_red", "mean_green", "mean_blue", "var_red", "var_green", "var_blue", "var_h", "var_s", "var_v") values ('5527', '0', '../../../../Bureau/estetimage/dump/008.jpg', '160', '0.0008', '2.8', '0', '0', '7', '51', '66', '147', '130', '141', '117', '50', '47', '32', '49', '47', '48');
insert into photo_param ("nbContours", "isPortrait", "path", "iso", "shutterspeed", "aperture", "focus", "nbfaces", "dominant_color", "global_hue", "global_saturation", "global_lightness", "mean_red", "mean_green", "mean_blue", "var_red", "var_green", "var_blue", "var_h", "var_s", "var_v") values ('2660', '0', '../../../../Bureau/estetimage/dump/009.jpg', '800', '0.00125', '10', '4294970000', '0', '7', '52', '111', '141', '128', '137', '100', '55', '59', '6', '48', '53', '54');
insert into photo_param ("nbContours", "isPortrait", "path", "iso", "shutterspeed", "aperture", "focus", "nbfaces", "dominant_color", "global_hue", "global_saturation", "global_lightness", "mean_red", "mean_green", "mean_blue", "var_red", "var_green", "var_blue", "var_h", "var_s", "var_v") values ('4861', '0', '../../../../Bureau/estetimage/dump/010.jpg', '200', '0.00625', '6.3', '0', '0', '7', '61', '73', '136', '121', '126', '116', '39', '30', '41', '44', '44', '36');
insert into photo_param ("nbContours", "isPortrait", "path", "iso", "shutterspeed", "aperture", "focus", "nbfaces", "dominant_color", "global_hue", "global_saturation", "global_lightness", "mean_red", "mean_green", "mean_blue", "var_red", "var_green", "var_blue", "var_h", "var_s", "var_v") values ('2271', '0', '../../../../Bureau/estetimage/dump/011.jpg', '50', '0.0125', '2.4', '0', '0', '7', '43', '83', '109', '100', '103', '87', '63', '57', '43', '9', '53', '63');
insert into photo_param ("nbContours", "isPortrait", "path", "iso", "shutterspeed", "aperture", "focus", "nbfaces", "dominant_color", "global_hue", "global_saturation", "global_lightness", "mean_red", "mean_green", "mean_blue", "var_red", "var_green", "var_blue", "var_h", "var_s", "var_v") values ('3705', '0', '../../../../Bureau/estetimage/dump/012.jpg', '100', '0.008', '5.6', '0', '0', '7', '41', '135', '153', '117', '152', '82', '56', '51', '44', '17', '54', '43');
insert into photo_param ("nbContours", "isPortrait", "path", "iso", "shutterspeed", "aperture", "focus", "nbfaces", "dominant_color", "global_hue", "global_saturation", "global_lightness", "mean_red", "mean_green", "mean_blue", "var_red", "var_green", "var_blue", "var_h", "var_s", "var_v") values ('2647', '0', '../../../../Bureau/estetimage/dump/013.jpg', '50', '0.0058072', '5.5', '0', '0', '7', '57', '106', '132', '122', '122', '97', '67', '65', '68', '56', '67', '68');